In [1]:
using CausalForest
using StatsBase
using Distributions

In [2]:
n, m = 10^4, 10
u = Uniform()
features = rand(u, (n, m))
X = [features; features]
T = convert(Vector{Int64},[ones(n); zeros(n)])
Y = X*[10, 0, 0, 0, 0, 0, 0, 0, 0, 0].*T  .+ 0.5

cf2 = build_forest(true, false, Y, T, X, true, 10, 500, 100);

In [3]:
importance(cf2)

10-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [4]:
Y = X*[10, 0, 0, 0, 0, 0, 0, 0, 0, 0].*T
cf3 = build_forest(true, false, Y, T, X, true, 10, 500, 100);

In [5]:
importance(cf3)

10-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [6]:
knn_sensi(cf2,500)

10×1 Matrix{Float64}:
 0.9918929774914527
 0.0006550416329902028
 0.0
 0.0003027146979698119
 0.0013085940791210695
 0.0008573639062424434
 0.0011308194739768095
 0.0012564125357778634
 2.2486405765928288e-5
 0.0025735897962739993

In [7]:
knn_sensi(cf3,500)

10×1 Matrix{Float64}:
 0.992071440167893
 0.00047778198533149184
 0.0
 0.00012553044589646634
 0.0011307659497374275
 0.0017614523934757855
 0.0009548787052569257
 0.0010805025743613646
 0.0
 0.0023976477937036837