In [1]:
using CausalForest
using StatsBase
using Distributions

In [2]:
n, m = 10^4, 10
u = Uniform()
features = rand(u, (n, m))
X = [features; features]
T = convert(Vector{Int64},[ones(n); zeros(n)])
Y = X*[10, 0, 0, 0, 0, 0, 0, 0, 0, 0].*T  .+ 0.5

cf2 = build_forest(true, false, Y, T, X, true, 10, 500, 100);

In [3]:
importance(cf2)

10-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [4]:
Y = X*[10, 0, 0, 0, 0, 0, 0, 0, 0, 0].*T
cf3 = build_forest(true, false, Y, T, X, true, 10, 500, 100);

In [5]:
importance(cf3)

10-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [6]:
knn_sensi(cf2,500)

10×1 Matrix{Float64}:
 0.9932709844489244
 9.533371339978032e-5
 0.0036841292944016584
 0.0011028442633642757
 0.0
 0.0
 0.0
 0.0018467083278862824
 0.0
 0.0

In [7]:
knn_sensi(cf3,500)

10×1 Matrix{Float64}:
 0.9934532227945371
 0.0
 0.0002470506134609272
 0.0023176049823706835
 0.0
 0.0023176049823714485
 0.0
 0.0016645166405752732
 0.0
 0.0