In [1]:
using CausalForest
using StatsBase
using Distributions

In [5]:
n, m = 10^4, 10
u = Uniform()
features = rand(u, (n, m))
X = [features; features]
T = convert(Vector{Int64},[ones(n); zeros(n)])
Y = X*[10, 0, 0, 0, 0, 0, 0, 0, 0, 0].*T  .+ 0.5

cf2 = build_forest(true, true, false, Y, T, X, false, 10, 1000);

In [6]:
importance(cf2)

10-element Vector{Float64}:
 0.7300094645732274
 0.03745396410017069
 0.020812147204470187
 0.021824037268353358
 0.019480863786476905
 0.05409698125638024
 0.021161083367197943
 0.02789464251637021
 0.02133018952715271
 0.04593662640020032

In [7]:
Y = X*[10, 0, 0, 0, 0, 0, 0, 0, 0, 0].*T
cf3 = build_forest(true, true, false, Y, T, X, false, 10, 1000);

In [8]:
importance(cf3)

10-element Vector{Float64}:
 0.7353374321413237
 0.03432356847298473
 0.019686600038485387
 0.021488649729176346
 0.01928051759025418
 0.05928653992036843
 0.020144270939010705
 0.02672023629779215
 0.0230434201873272
 0.040688764683277

In [9]:
knn_sensi(cf2,500)

10×1 Matrix{Float64}:
 0.9561128801981618
 0.0
 0.0
 0.0010179326924024418
 0.00357997707986574
 0.0099070946548205
 0.0
 0.020561706303463958
 0.0012513396861744536
 0.007569068156700994

In [10]:
knn_sensi(cf3,500)

10×1 Matrix{Float64}:
 0.9527755807164225
 0.005025726627649012
 0.0
 0.03257733724951108
 0.0
 0.005877720426312743
 0.0
 0.0
 0.0
 0.0037436335498482417